### ISSUE TITLE
What is the meaning of these lines in rollup.config.js?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/component-template#30]
What is the meaning of these lines?

https://github.com/sveltejs/component-template/blob/master/rollup.config.js#L5-L8

```js
const name = pkg.name
	.replace(/^(@\S+\/)?(svelte-)?(\S+)/, '$3')
	.replace(/^\w/, m => m.toUpperCase())
	.replace(/-\w/g, m => m[1].toUpperCase());
```

Thanks.

**Comment by Conduitry** [comment]
They automatically generate a UMD module name from the `package.json` `name`.

**Comment by frederikhors** [comment]
Yes, I know, but why do we need `.replace(/^(@\S+\/)?(svelte-)?(\S+)/, '$3')`?

If the project name in pkg.json is `my-project` or maybe `@organization/project-name`, what's the meaning of that regex?

**Comment by ignatiusmb** [comment]
It removes the scoped name `@organization` and `svelte-`, `$3` means to only take the third capturing group.

`@organization/svelte-custom-component` will be reduced to only `custom-component`

**Comment by frederikhors** [comment]
Ok. Thanks, @ignatiusmb.

And why?

Is there a problem in leaving original org and project name in UMD?

**Comment by ignatiusmb** [comment]
UMD builds needs a namespace to call the package from, either directly by the name or with `window.`

Having `@` would probably cause an error, and I would also personally not include my org name for the sake of simplicity, wouldn't want the users to call `window.MyOrganizationNameMyCustomComponent` every time they want to use it. The original project name is always used except when it has `svelte-`, probably because if they're using the package it already implies that they know it's a Svelte component, so having to write Svelte as a prefix is redundant.

You could totally just write your own name and not use the name in `package.json`, this template is made so the users wouldn't need to think about the UMD build.
